### ISSUE TITLE
Add a migration for the migration table

### ISSUE THREAD

**Issue by kenrestivo-stem** [yogthos/migratus#107]
Anyone upgrading to 0.9.1(as opposed to starting a new project with it)  will have a breaking change, as the schema for the migration table has changed.

I'll need to add a migration for the migration table, to add the 
```clojure
[:applied "datetime" "" ""]
[:description "VARCHAR(1024)" "" ""]
```

**Comment by yogthos** [comment]
Thanks, I added a [CHANGES.md](https://github.com/yogthos/migratus/blob/master/CHANGES.md) file to track this stuff.

**Comment by Macroz** [comment]
This was a yo dawg moment to me to realize that the tool I'm using for migrations breaks its own database on a version database. Somehow I expected Migratus to handle this kind of thing by itself.

**Comment by yogthos** [comment]
That's actually not a bad idea. The db migrations schema could also contain a version, and migratus could try to migrate to the newer version automatically.

**Comment by yogthos** [comment]
Although this is the first time it's come up, I can't imagine that the migrations table will get a lot more complex in the future. ;)

**Comment by Macroz** [comment]
It seems impossible to write adding of the missing columns as a migration, since can't run the migrations without the columns already existing. Also since Migratus creates the `schema_migrations` table itself, it should take care of its columns also by itself.

**Comment by kenrestivo-stem** [comment]
This caused us a bit of grief. It is indeed a meta-migration: migrating the migrator.

It might not be bad to have it check on every migration whether the DB is up to date.

**Comment by yogthos** [comment]
Yeah I think that would make sense. It should do a sanity check to make sure the schema is correct at the very least.
