### ISSUE TITLE
0.9.1 breaks directory scanning

### ISSUE THREAD

**Issue by kenrestivo-stem** [yogthos/migratus#108]
```
                          migratus.core/migrate        core.clj:   69
                              migratus.core/run        core.clj:   25
                        clojure.core/partial/fn        core.clj: 2598
                         migratus.core/migrate*        core.clj:   62
           migratus.core/uncompleted-migrations        core.clj:   40
            migratus.migrations/list-migrations  migrations.clj:  119
                             clojure.core/doall        core.clj: 3121
                             clojure.core/dorun        core.clj: 3115
                              clojure.core/next        core.clj:   64
                                            ...                      
    migratus.migrations/list-migrations/iter/fn  migrations.clj:  122
             migratus.migrations/make-migration  migrations.clj:  111
java.lang.Exception: Multiple migration types specified for migration 20170502184444 ("sql" "sql~")
Multiple migration types specified for migration 20170502184444 ("sql" "sql~")
```

Some years ago I remember adding a check to ignore files with extensions to do with temp files, etc. Looks that got regressed.

I can fix this if you like; your call.

**Comment by yogthos** [comment]
Yeah that might get confusing, probably would be good to filter that. :)

**Comment by yogthos** [comment]
Thinking a bit more about this, might make sense to allow specifying the file pattern as a regex in the config map. In principle the migrations aren't restricted to SQL as the protocol can be implemented using any custom method.

Filtering using the supplied pattern and falling back to a pattern for temp files as the default would be ideal.

**Comment by kenrestivo-stem** [comment]
Seems reasonable. I'd put it in the code; right now AFAICT there are only two types supported: "*.sql" and "*.edn". As support for newer types are added, one could update the regexp list?

**Comment by yogthos** [comment]
Currently, Migratus is agnostic regarding the extension since the file pattern is defined as:

```clojure
    (def migration-file-pattern #"^(\d+)-([^\.]+)((?:\.[^\.]+)+)$")
```

The edn/sql implementations are packaged, but the user could provide their own. It could make sense to keep this in code as part of the code that implements the protocol though.

**Comment by kenrestivo-stem** [comment]
I'm game for either; the only thing that's important for me (and every other Emacs user who uses Migratus) is that it doesn't try to process files with "~" appended. Do you want to make the change or should I take a pass at it?

**Comment by yogthos** [comment]
If you could take a pass that would be great. :)

**Comment by yogthos** [comment]
I'm also ok with either having the extension being part of the namespace implementing the protocol, or a config parameter. Whichever one is more convenient.

**Comment by kenrestivo-stem** [comment]
It seems cleaner to have it with the protocol. Will look at it over the next day or two.

**Comment by yogthos** [comment]
sounds like a plan

**Comment by kenrestivo-stem** [comment]
Submitted a patch, let me know if you want a different approach or any changes.

**Comment by yogthos** [comment]
looks good to me, and I think it covers everything we talked about. :)

**Comment by yogthos** [comment]
fixed by https://github.com/yogthos/migratus/pull/110

**Comment by yogthos** [comment]
just pushed out a new version with the fix, thanks for getting it in so quick 👍
