### ISSUE TITLE
Cannot create migrations table in PostgreSQL

### ISSUE THREAD

**Issue by OlegTheCat** [yogthos/migratus#109]
```
user> (migratus/migrate config)
17-05-03 14:58:36 host INFO [migratus.core:288] - Starting migrations
17-05-03 14:58:36 host INFO [migratus.database:288] - creating migration table 'migrations'
17-05-03 14:58:36 host INFO [migratus.core:288] - Ending migrations
PSQLException ERROR: type "datetime" does not exist
  Position: 61  org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2455)
```

I'm getting this error when trying to create migrations table in PostgreSQL. Seems that PostgreSQL is not aware what `datetime` is, and `timestamp without time zone` should be used instead.

**Comment by OlegTheCat** [comment]
I've manually created the migrations table and seems that `timestamp without time zone` doesn't work either:

```

**Comment by yogthos** [comment]
Hi, I just pushed out 0.9.2 with a fix. I switched to use timestamp as the field and fixed the code to write the timestamp correctly. Let me know if it works for you.

**Comment by OlegTheCat** [comment]
Will try it right away

**Comment by OlegTheCat** [comment]
Yep, it works. Thanks for the quick response and fix 👍

**Comment by yogthos** [comment]
👍

**Comment by gsnewmark** [comment]
It looks like `timestamp` won't work in SQL Server:

> The Transact-SQL timestamp data type is different from the timestamp data type defined in the ISO standard
https://docs.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql

Value for it is automatically generated on each row update and can't be inserted manually. I don't actually have any experience with SQL server, so maybe I'm mistaken. 

Not sure if there is need to create/reopen issue as it looks like nobody even uses Migratus with SQL Server (based on the issue tracker).

**Comment by yogthos** [comment]
I don't have a copy of SQL server handy to test with. I agree that it's an unlikely target, so probably safe to keep the issue closed until this comes up.

**Comment by kenrestivo-stem** [comment]
Will change to timestamp
