### ISSUE TITLE
Run "down" automatically if an "up" fails

### ISSUE THREAD

**Issue by kenrestivo-stem** [yogthos/migratus#111]
Here's the scenario:

1. Run a migration with several schema changes (add column, add table, etc)
2. One of those towards the end of the migration fails.
3. The earlier ones are *not* rolled back because MySQL automatically commits on any DDL changes https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html
4. You now can't apply the migration, and it isn't marked as applied either, and the with-db-transaction was basically useless.
5. You can't run "down" because "down" checks to see if the migration was applied first, and won't run the down if the up was successful
6. You are now stuck.

I'd suggest either:
a. running "down" automatically-- to back out any changes--  if an "up" fails
b. allowing "down" to be run manually by deploy scripts or devops even if the migration hasn't yet been successfully applied, to back out the failed migration
c. both

Again, happy to submit a patch to do either or both.

**Comment by yogthos** [comment]
I think migrations should be transactional from user perspective. It would make sense to track migration steps as they're applied, and then roll them them back in the `catch` block if any exceptions are thrown. So option a would be my preference. A patch would be very welcome. :)

**Comment by kenrestivo-stem** [comment]
OK, will do!

**Comment by yogthos** [comment]
👍

**Comment by kenrestivo-stem** [comment]
I was thinking of running the down only if the up fails specifically with a com.mysql.jdbc.SQLError.createSQLException , since AFAICT only MySQL InnoDB exhibits this broken behavior of not being able to reverse a schema change (e.g, h2 has no problem with it). Might require a bit of macro magic as that Exception will only exist if the mysql jdbc lib is loaded, but I am going to try that approach first.

**Comment by yogthos** [comment]
What's the downside of just rolling back the migrations that were applied on any errors? My thinking is that you'd want to either apply all the migrations in the current set or none at all. If any of the migrations steps fail for any reason, you likely don't want to have a partially applied migration at that point.

**Comment by kenrestivo-stem** [comment]
Hmm, that'd make life a lot simpler, for sure. Will try that approach

**Comment by kenrestivo-stem** [comment]
That works. Writing some test cases to make sure it doesn't regress in the future, then will submit a pull request

**Comment by yogthos** [comment]
Fantastic, this will be a great addition. :)
