### ISSUE TITLE
Handle migrating the migratus schema itself automatically

### ISSUE THREAD

**Issue by kenrestivo-stem** [yogthos/migratus#113]
Raised by https://github.com/Macroz in  https://github.com/yogthos/migratus/issues/107

**Comment by kenrestivo-stem** [comment]
I can take a stab at this next week perhaps.

**Comment by yogthos** [comment]
@kenrestivo-stem fantastic, thanks again for all the help with the project!

**Comment by csapp** [comment]
Just curious if there are any updates on this? We're looking to leverage some of the new migratus features in our app but we're struggling with this. Thanks!

**Comment by kenrestivo-stem** [comment]
Sorry, got pulled off of this onto other things. Will try to tackle it soon.

**Comment by kenrestivo-stem** [comment]
Updated here https://github.com/yogthos/migratus/pull/118

Hey, if anyone on here wants to volunteer to update the test cases, that'd be great. I didn't have time to get to that.

**Comment by yogthos** [comment]
merged the pr and released

**Comment by csapp** [comment]
Thanks so much, guys!
