### ISSUE TITLE
Version 0.9.3 clojars code doesn't match github

### ISSUE THREAD

**Issue by kenrestivo-stem** [yogthos/migratus#114]
In github, 0.9.3 has this:
https://github.com/yogthos/migratus/blob/master/src/migratus/database.clj#L67

But in the 0.9.3 jar pulled from clojars, it has:

```clojure
      (try
        (sql/with-db-transaction
          [t-con db]
          (when-not (complete? t-con table-name id)
            (proto/up migration (assoc config :conn t-con))
            (mark-complete t-con table-name name id)
            :success))
        (finally
          (mark-unreserved db table-name)))
```

which is actually 0.9.2.

Oddlly, the project.clj inside of the jar says 0.9.3

**Comment by yogthos** [comment]
yeah I think I screwed up the tag for that release, I noticed that when pushing out 0.9.4

**Comment by kenrestivo-stem** [comment]
Thanks! That worked.
