### ISSUE TITLE
init task always runs in transaction with Postrgres

### ISSUE THREAD

**Issue by hackeryarn** [yogthos/migratus#117]
`(migratus/init config)` cannot run with `CREATE DATABASE` while using Postgres because it is always wrapped in a transaction.

### Workaround:
Add `END;` at the top of your `init.sql` file. This will break you out of the transaction before running the rest of the migration.

**Comment by lellisga** [comment]
this is throwing a `java.lang.NullPointerException` could you please show me your `config`. Thanks

**Comment by lane-s** [comment]
I'm experiencing this as well. I have `:init-in-transaction? false` in my config when calling `migratus/init`

**Comment by willolisp** [comment]
+1

**Comment by mikeananev** [comment]
I've fixed this error. See PR https://github.com/yogthos/migratus/pull/174
