### ISSUE TITLE
Adding support for multiple resource directories

### ISSUE THREAD

**Issue by McNullty** [yogthos/migratus#120]
Hi, I was trying out your library and it's really cool, but I have one suggestion.

I would like to have some migration scripts that I would like to run only in dev environment. I have resource/migrations/ directory for normal migrations and env/dev/resource/migrations/ for dev migrations. Now if I run `lein migratus migrate` migratus will find first migrations directory on classpath and run only files in that directory.
I made workaround by creating new profile where I have made :migration-dir "../env/dev/resources/dev-migrations" and I run `lein migratus migrate` and then `lein with-profile dev,dev-migrations migratus migrate`
I think it would be better to gather files from all migrations directories and then run them in order of their ID number. I anticipate problem with create method, because with multiple migrations directories you wouldn know in which one to put new files.

If you think this would be good solution I could try to make PR with solution.

Thanks,
Mladen

**Comment by yogthos** [comment]
The profile approach is actually not bad, and you could create an alias to avoid having to type that in each time:

```clojure
{"migrate-dev" ["with-profile" "dev,dev-migrations" "migratus" "migrate"]}
```

**Comment by McNullty** [comment]
OK, closing issue
