### ISSUE TITLE
Suggestion: UTC timestamps

### ISSUE THREAD

**Issue by leblowl** [yogthos/migratus#131]
I noticed the migration timestamps are in the user's system time. I haven't actually found the official Javadocs that describe this behavior but I found some references to it (e.g. https://eyalsch.wordpress.com/2009/05/29/sdf/) and have verified the behavior on my system: 
```
user=> (let [fmt (SimpleDateFormat. "yyyyMMddHHmmss ")]
  #_=>  (.format fmt (Date.)))
"20180130215514 "
user=> 
[1]+  Stopped                 lein repl
lucas@debian:~/Code/leblowl/clj-wiki$ date
Tue Jan 30 21:55:22 MST 2018
```
I have read that it's a side effect of SimpleDateFormat.

I can imagine a case where one might have difficulty in a distributed project when creating migrations if the timestamps are in the user's local time. There could be one case where developer A in UTC-3 is working on the same codebase as developer B in UTC-5. Developer A may commit a new migration that developer B picks up immediately. If developer B then immediately creates a new migration, developer B's migration may be numerically before Developer A's migration, even though it should be run afterward.

If migrations are executed in order solely based on the timestamp, then I suggest UTC timestamps. Here is a little snippet I came up with for the migrations/timestamp function that should output a UTC timestamp (relies on java.util.TimeZone):
```clojure
(let [fmt (SimpleDateFormat. "yyyyMMddHHmmss ")
      utc-tz (TimeZone/getTimeZone "UTC")]
  (.setTimeZone fmt utc-tz)
  (.format fmt (Date.)))
```

**Comment by yogthos** [comment]
That's a great catch, UTC is definitely safer for distributed teams. Just pushed out an update with the fix. 👍

**Comment by leblowl** [comment]
Awesome, thanks
