### ISSUE TITLE
Only insert supported for migration data?

### ISSUE THREAD

**Issue by WorldsEndless** [yogthos/migratus#137]
Using postgres, default pg_dump uses the optimized COPY directive to insert stuff. This doesn't seem to work with MIgratus. Am I missing anything?

**Comment by yogthos** [comment]
Migratus should be agnostic regarding the content of the queries, it just runs them directly via [clojure.java.jdbc](https://github.com/clojure/java.jdbc) that's in turn a thin wrapper around the JDBC implementation.
