### ISSUE TITLE
Migratus runs for about 60 seconds after completing migrate

### ISSUE THREAD

**Issue by rplevy** [yogthos/migratus#147]
The last log info is: `2018-09-11 16:48:12,533 [main] INFO  migratus.core - Ending migrations` but it doesn't exit for another whole minute.

Seems to be due to this line:

https://github.com/yogthos/migratus/blob/6aacc913721f1feb66afeddd8ba620e334665dd8/src/migratus/core.clj#L30

What is the benefit of freeing resources?  Can this just be omitted and exit immediately?

**Comment by yogthos** [comment]
The delay may be a symptom of a large transaction being committed, I haven't noticed long delays in a general case. Disconnecting ensures that the transactions are flushed to the database before Migratus exits.

**Comment by dijonkitchen** [comment]
`lein migratus migrate` seems to take a while to spin-up and spin-down, even when there are no new migrations.

**Comment by yogthos** [comment]
Some of that comes from `lein` itself being fairly slow. My recommendation is to use Migratus via the REPL as much as possible. For example, you could add something like the following in `user.clj`:

```clojure
(def config {...})

(defn reset [config]
  (migratus/reset config))

(defn destroy [config & [id]]
  (if id
    (migratus/destroy config id)
    (migratus/destroy config)))

(defn pending [config]
  (migratus/pending-list config))

(defn migrate [config & args]
  (if (> (count args) 0)
    (apply migratus/up config (parse-ids args))
    (migratus/migrate config)))

(defn rollback [config & args]
  (if (> (count args) 0)
    (apply migratus/down config (parse-ids args))
    (migratus/rollback config)))
```
