### ISSUE TITLE
ms sql 2016 timestamp field 

### ISSUE THREAD

**Issue by slowcod** [yogthos/migratus#148]
The migration's table applied field of type timestamp throws the following SQL Exception 
"Cannot insert an explicit value into a timestamp column.
Use INSERT with a column list to exclude the timestamp
column, or insert a DEFAULT into the timestamp column."

Changing the table definition to 
"CREATE TABLE [dbo].[mymigrations](
	[id] [bigint] NOT NULL PRIMARY KEY,
	[applied] [datetime] NULL,
	[description] [varchar](1024) NULL);"
works well.

**Comment by yogthos** [comment]
Looks like Migratus would need to be a way to detect the type of the database to create the appropriate column types. This can probably be inferred from the connection. I'll try to take a look when I get a bit of time, but if you'd be up for making a PR I could help with that as well.
