### ISSUE TITLE
Failure: Query returns results

### ISSUE THREAD

**Issue by urzds** [yogthos/migratus#149]
When trying to use the following migration file with `[org.xerial/sqlite-jdbc "3.25.2-SNAPSHOT"]` (needs https://github.com/xerial/sqlite-jdbc/issues/368) against an SQLite3 database, migratus aborts with an error: `Failure: Query returns results`

```sql
ALTER TABLE applications RENAME COLUMN logo TO logo_url;
```

When executing the same query in the `sqlite3` CLI program, I see no "result" being printed:
```
sqlite>  ALTER TABLE applications RENAME COLUMN logo TO logo_url;
sqlite>
```

I would like to know how to prevent this error / how to discard the result.

**Comment by urzds** [comment]
This is the result of using `clojure.java.jdbc` in a REPL directly:
```clj
(require 'clojure.java.jdbc)
;;=> nil
(def db-spec {:dbtype "sqlite" :dbname "db.sqlite3"})
;;=> #'user/db-spec
(clojure.java.jdbc/query db-spec ["ALTER TABLE applications RENAME COLUMN logo_url TO logo"])
;;=> ()
```

**Comment by devurandom** [comment]
> Would you happen to have a test project I can look at.

No open source code, sadly.

> It doesn't look like 3.25.2-SNAPSHOT is up in public Maven repos, what's the process for building it?

Two possibilites:
* Get @xerial to to tackle https://github.com/xerial/sqlite-jdbc/issues/368 and then use his build from Maven
* Or apply the following PRs and build a JAR from it afterwards, which you can `lein deploy` into a test project:
  - https://github.com/xerial/sqlite-jdbc/pull/372
  - https://github.com/xerial/sqlite-jdbc/pull/373
  - https://github.com/xerial/sqlite-jdbc/pull/374

**Comment by devurandom** [comment]
> Just released sqlite-jdbc 3.25.2

Thanks a lot!

**Comment by yogthos** [comment]
Ok, I can reproduce the issue locally with the latest version. The problem seems to be with `db-do-prepared` throwing an error [here](https://github.com/yogthos/migratus/blob/b9581b19d8746307da071ae9f4c89161c8f8e220/src/migratus/migration/sql.clj#L31). The error is reproducible by running the command directly:

```
(jdbc/db-do-prepared
  {:connection-uri "jdbc:sqlite:test.db"}
  "ALTER TABLE applications RENAME COLUMN logo TO logo_url")
```

I'll take a look at switching to `db-do-commands` instead.

**Comment by yogthos** [comment]
Just pushed out `migratus 1.1.0` to Clojars with the fix, let me know if everything looks good.
