### ISSUE TITLE
Bug has returned

### ISSUE THREAD

**Issue by fl00r** [yogthos/migratus#153]
Hi!

I see a commit

https://github.com/yogthos/migratus/commit/4eac6152bb6f35f3e1bc6a32fccdd64f85bc9f58

which inverts this commit 

https://github.com/yogthos/migratus/commit/76b71e102ecc2ebc7d2ba0ab6c09d3b1446c4fe4

and an old bug is here again (https://github.com/yogthos/migratus/issues/42, https://github.com/yogthos/migratus/issues/41#issuecomment-146034134)

**Comment by yogthos** [comment]
Hi,

The change was made for [this issue](https://github.com/yogthos/migratus/issues/149), as `db-do-prepared` throws an error for that case. If you have a suggestion for how we could handle both cases that would be great.

**Comment by fl00r** [comment]
Ok I see

**Comment by fl00r** [comment]
I've sent a pull request.

But the problem is that if one needs to run a number of commands it's better to use batching instead of concatenating those commands, I suppose.

**Comment by fl00r** [comment]
But that's out of your scope because you just run arbitrary texts... then the solution would be by splitting those commands with ";"

**Comment by fl00r** [comment]
I think that `#";"` is not a very strong regexp, but in most cases it should work

**Comment by yogthos** [comment]
Thanks for the PR, I just pushed out version `.1.1.2` with the fix.
