### ISSUE TITLE
NPE when init file is set on windows

### ISSUE THREAD

**Issue by slowcod** [yogthos/migratus#158]
On windows in the find-init-script-resource fn the init-script-path results with backslash as path separator whereas the jar's entries have forward slash, never matching the filter predicate (.endsWith (.getName entry) init-script-path)

**Comment by yogthos** [comment]
I don't actually have a windows machine to test with. I can help guide a PR along though if you'd be interested.

**Comment by yogthos** [comment]
fixed by https://github.com/yogthos/migratus/pull/159
