### ISSUE TITLE
problem with command separator

### ISSUE THREAD

**Issue by dpsutton** [yogthos/migratus#165]
I've run into an issue with using the command separator
```clojure
(def config {:command-separator ";"})
```
This works fine unless you run across the following type of statement:
```sql
DO $$
DECLARE conflicts record;
integer_var int;
...
END$$
```

Here if you chop up the statements at each `;` you will break the `DO $$` statement. I'm not too versed in sql so I'm not sure how many statements are like this (maybe do, begin, maybe others?). But outside of actually parsing the commands, would it be acceptable to suppress the command separator in certain contexts?

**Comment by yogthos** [comment]
Yeah, it's fine to omit the command separator, unless you need to explicitly split statements into separate commands. In general, I would discourage using `;` as a command separator as it overloads its existing meaning in SQL.
