### ISSUE TITLE
Suggestion: Allow passing in a connection

### ISSUE THREAD

**Issue by snorremd** [yogthos/migratus#171]
Would it make sense to pass in an existing connection instance to migratus instead of specifying a db connection map?

Ref: https://github.com/yogthos/migratus/issues/90#issuecomment-250065862

I use a Hikari connection pool in a project and have logic to configure and create db connections already. It would be nice if that logic could be reused when dealing with migrations. As far as I can tell this feature would only require small modifications of the [`connect*`](https://github.com/yogthos/migratus/blob/master/src/migratus/database.clj#L113) function. The function could check if `db` is an instance of a connection, or contains a `:connection` key and if so forgo creating the connection.

**Comment by yogthos** [comment]
That sounds reasonable to me, would you be up for doing a PR to add that? :)

**Comment by snorremd** [comment]
Sure thing.

**Comment by yogthos** [comment]
👍

**Comment by snorremd** [comment]
Solved as of #172.
