### ISSUE TITLE
support group migrations

### ISSUE THREAD

**Issue by vinurs** [yogthos/migratus#175]
in resources/migrations directories, i want to group the sql files by sub-directory, then when i run
```
java -Dconf=prod-config.edn -jar suoyan-admin.jar migrate
```
it shows the error:
>2019-10-23 10:07:02,211 [main] WARN  migratus.migrations - skipping: 'user/20190222174644-create-oauth-refresh-token-table.up.sql' migrations must match pattern: ^(\d+)-([^\.]+)((?:\.[^\.]+)+)$

**Comment by yogthos** [comment]
That sounds reasonable to me. I might not have time in the near future, but I'm open to a PR if you get a chance before I do.

**Comment by vinurs** [comment]
i have send a PR for this
