### ISSUE TITLE
Add ability to exclude files by mask

### ISSUE THREAD

**Issue by p-himik** [yogthos/migratus#177]
Use case: for CLJ migrations it makes sense to put the CLJ files among with the SQL and EDN files or in a subdirectory within the migrations directory.
Right now this approach causes migratus to spew out a warning for each such file like this:
```
WARN migratus.migrations - skipping: 'blah.clj' migrations must match pattern: ^(\d+)-([^\.]+)((?:\.[^\.]+)+)$
```
IMO it would make sense to just exclude `*.clj` in this case.

**Comment by p-himik** [comment]
An alternative - exclude a particular subdirectory.

**Comment by yogthos** [comment]
That sounds reasonable, I'd be open for a PR to add that.

**Comment by p-himik** [comment]
Took me some time. :)

**Comment by yogthos** [comment]
Thanks, just pushed out `1.4.6` with the changes. Would you mind adding a usage example for the readme as well? :)
