### ISSUE TITLE
migratus.core/select-migrations leaks DB connections

### ISSUE THREAD

**Issue by griff** [yogthos/migratus#185]
The function `migratus.core/select-migrations` never calls disconnect and so if called repeatedly leaks a DB connection on each call.

I use a DB pool and was testing my migrations and migratus and so was calling `migratus.core/completed-list` and `migratus.core/pending-list` a lot and that is when I discovered this issue since my pool would run out of connections pretty quickly.

**Comment by yogthos** [comment]
Oh that's a good catch, would you be ok to do PR for the fix?
