### ISSUE TITLE
:migration-dir is always have value "migrations/"

### ISSUE THREAD

**Issue by mikeananev** [yogthos/migratus#188]
Hi!

:migration-dir is always have value "migrations/" when calling (migratus/create config "anyname")

Mike

**Comment by yogthos** [comment]
Hmm, I'm not able to reproduce this locally. The code for create is [here](https://github.com/yogthos/migratus/blob/6a6f96a93bfa64cf6aae729c72732912e6ef2c02/src/migratus/migrations.clj#L148)

```clojure
(defn create [config name migration-type]
  (let [migration-dir  (find-or-create-migration-dir
                         (utils/get-parent-migration-dir config)
                         (utils/get-migration-dir config))
        migration-name (->kebab-case (str (timestamp) name))]
    (doseq [mig-file (proto/migration-files* migration-type migration-name)]
      (.createNewFile (io/file migration-dir mig-file)))))
```

it checks for the parent migration dir and the migration dir to create the path, and both functions check the value in the config. If you run it with

```clojure
(let [config {:migration-dir "foo"}]
    (find-or-create-migration-dir
      (utils/get-parent-migration-dir config)
      (utils/get-migration-dir config)))
```

The result is `"resources/foo"` which is what I'd expect.

**Comment by mikeananev** [comment]
Hi, Dmitry!

My mistake. I put :migration-dir inside :db section.
Thanks.
