### ISSUE TITLE
When error happens, db password information is shown

### ISSUE THREAD

**Issue by pinkfrog9** [yogthos/migratus#220]
This piece of information should better be hidden.

**Comment by yogthos** [comment]
Agreed, this would be good to omit in the log. Would you be up for making a PR for this by any chance?

**Comment by pinkfrog9** [comment]
Hi @yogthos. Would you please look at: https://github.com/yogthos/migratus/pull/222

**Comment by yogthos** [comment]
Thanks looks good, there are a few other fixes in the works, so I'll cut a new release next week.

**Comment by ieugen** [comment]
Relates to https://github.com/yogthos/migratus/issues/189 .
Possible duplicate.

**Comment by ieugen** [comment]
This was released as part of 1.4.0
