### ISSUE TITLE
next.jdbc does not support :connection-uri style :db (yet)

### ISSUE THREAD

**Issue by seancorfield** [yogthos/migratus#221]
Your docs show three ways to specify the `:db` for migrations:
* a "db-spec" hash map with `:dbtype`/`:dbname`/etc
* a hash map containing `:connection-uri`
* a string providing the connection URI (the JDBC URL)

While that worked for `clojure.java.jdbc`, the second form has not been accepted by `next.jdbc` so far.

A couple of c.j.j compatibility issues have come up recently, as far as the "db-spec" hash map is concerned so I've just implemented https://github.com/seancorfield/next-jdbc/issues/207 -- I'll try to remember to bump this issue when I cut the next release and you can bump the dependency in Migratus.

**Comment by seancorfield** [comment]
A follow-up: if you are just passing the value of `:db` straight through to `next.jdbc`, you might want to note in the documentation that it can be anything `next.jdbc/get-connection` (or `next.jdbc/get-datasource`) can accept.

**Comment by seancorfield** [comment]
FYI, just to close the loop, `next.jdbc` 1.2.790 has been released with support for that `{:connection-uri ...}` format (as well as raw `{:datasource ...}` without `:user`/`:password`).

**Comment by yogthos** [comment]
Thanks for the heads up, I've updated the dependency. Should be a release sometime next week with a few fixes.

**Comment by ieugen** [comment]
Updated readme and changelog to mention this. 
Fixed in latest release 1.4.0
