### ISSUE TITLE
Paths with "+" characters result in NoSuchFileException

### ISSUE THREAD

**Issue by dpassen** [yogthos/migratus#226]
https://github.com/yogthos/migratus/blob/d14b3d683b8c1aa5b9fcedc7a5879c2ae3434717/src/migratus/utils.clj#L45 ends up replacing "+" with " " when the path to the jar file contains it.

When my team upgraded leiningen from 2.9.8 to 2.9.10, our uberjar was put into target/default+uberjar/... and we lost the ability to run our migrations from within the uberjar

**Comment by yogthos** [comment]
Would you be up to do a pr for a fix here? :)

**Comment by dpassen** [comment]
Sure. Just have to decide what the right solve is.
