### ISSUE TITLE
[BUG] up / down don't appear to be working with code-based migrations

### ISSUE THREAD

**Issue by sirmspencer** [yogthos/migratus#239]
code-based migrations are super cool by the way.  I have everything set up and running migrate picks up on the code-based migrations.  up and don't don't seem to.  I am using the same config, etc as our SQL migrations that do work with up and down.

**Comment by yogthos** [comment]
Have you added the up/down fn declarations?

```clojure
{:ns app.migrations.import-users
 :up-fn migrate-up
 :down-fn migrate-down
 :transaction? true}
```

**Comment by sirmspencer** [comment]
Yes.  And migratus/migrate works by calling the up function.

**Comment by sirmspencer** [comment]
Its working now.  Not sure what happened.

**Comment by yogthos** [comment]
Hmm, maybe stale repl state.
