### ISSUE TITLE
Allow managing the connection state from calling code

### ISSUE THREAD

**Issue by b-ryan** [yogthos/migratus#255]
Discussion:

https://github.com/yogthos/migratus/issues/253#issuecomment-1819840435

https://github.com/yogthos/migratus/issues/253#issuecomment-1819854502

I wonder if the implementation will be easier by allowing the db map to look like:

```clojure
{:connection ... :managed-connection? true}
```

If so it looks to me like the feature could be achieved by modifying `migratus.core/run` to:

```clojure
(defn run [store ids command]
  (try
    (log/info "Starting migrations")
    (proto/connect store)
    (command store ids)
    (catch java.sql.BatchUpdateException e
      (throw (or (.getNextException e) e)))
    (finally
      (log/info "Ending migrations")
      (when-not (:managed-connection? (:db (:config store))) (proto/disconnect store)))))
```

Dunno if this is how you'd want this implemented or whether it covers every case though.

**Comment by b-ryan** [comment]
Maybe the robust way would be to have a separate implementation of `Store` that does nothing inside `disconnect`.

**Comment by yogthos** [comment]
Yeah, I think that would be cleaner. The store implementation could be selected based on the config, and then everything else should work same as before.
