### ISSUE TITLE
Using `migratus.cli` programmatically warns about `parse-long` being replaced

### ISSUE THREAD

**Issue by p-himik** [yogthos/migratus#266]
I know that it's probably not the intended usage of `migratus.cli`, but there's no other reasonable way to achieve what I want:
- Supplying custom config populated by Aero
- Fully disabling "down" migrations
- Using templates for EDN migrations
- Printing URLs to created files so they become easy to navigate to from within an IDE

Of course, each of the items could be its own issue that could also be eventually solved, but just the first item already requires me to use Migratus as a library, I think.

So, what I ended up doing is requiring `migratus.cli` in my own CLI script and calling `migratus.cli/run-migrate`, `migratus.cli/up`, `migratus.cli/run-list` with the right config. And it ends up in:
```
WARNING: parse-long already refers to: #'clojure.core/parse-long in namespace: migratus.cli, being replaced by: #'migratus.cli/parse-long
```

**Comment by yogthos** [comment]
The warning just means that `parse-long` is masking the version that was introduced in recent Clojure standard library. I've added an exclusion for parse-long in `1.5.7`, let me know if everything looks good on your end now.

**Comment by p-himik** [comment]
Perfect, thank you!
