### ISSUE TITLE
Migratus CLI requires `clojure.data.json` but the jar does not specify the dependency

### ISSUE THREAD

**Issue by p-himik** [yogthos/migratus#272]
I see that `deps.edn` lists `clojure.data.json` as a dependency, but `project.clj` doesn't. I suspect that the JAR is generated from `project.clj` hence the missing dependency.

**Comment by yogthos** [comment]
Yup, missed adding it in project.clj, just pushed out `1.6.2` with the dependency added.

**Comment by p-himik** [comment]
For my own understanding - is `project.clj` there only because of historical reasons (and consequent current usage)? Or are there things that aren't easily achievable with `deps.edn` and `build.clj`?

**Comment by yogthos** [comment]
Yeah, `project.clj` is how it was set up historically, and I still use it to package the jar when doing releases. It could definitely be done using `deps.edn` and `build.clj` going forward. I just haven't got around to switching that around.

**Comment by p-himik** [comment]
@yogthos Just cleaned up a project of mine and stumbled upon another dependency error from Migratus - this time it's about missing `org.clojure/tools.cli`.

**Comment by yogthos** [comment]
oh yeah totally missed that, ok 1.6.3 should have dependencies in sync with what's in deps
