### ISSUE TITLE
Validate the migration ids that are passed in

### ISSUE THREAD

**Issue by pjstadig** [yogthos/migratus#3]

**Comment by ndrluis** [comment]
what type of validations?

Verify the create date with the timestamp on filename?
Verify the filename has a correct timestamp pattern?

**Comment by yogthos** [comment]
Looks like this might be done already. The [find-migration-files](https://github.com/yogthos/migratus/blob/77cfb6f9d3437b835bb5954b3f53a82f3a410bcc/src/migratus/database.clj#L117) function will warn if it's unable to parse the filename.

**Comment by jumarko** [comment]
@yogthos not sure what @pjstadig meant by this by I can confirm that validation works for cases like "*-up.sql" (it should be "*.up.sql"). In that case, the error message is clear.

It there's no other reason to leave this issue open I suggest to close it.

**Comment by yogthos** [comment]
sounds good to me
