### ISSUE TITLE
Insert in "compound" migration causes constraint violation

### ISSUE THREAD

**Issue by tdavis** [yogthos/migratus#31]
I have a migration that looks something like:

```sql
INSERT INTO users (id, ...) VALUES (1, ...);
--;;
SELECT nextval('users_id_seq');
```

With a completely empty database, this migration inserts the row then fails with ``ERROR: duplicate key value violates unique constraint "users_pkey"`` from attempting to insert the same row a second time. If I remove the second portion of the migration, it succeeds. Unfortunately, that leaves the database in an unusable state.

**Comment by yogthos** [comment]
should be addressed by https://github.com/yogthos/migratus/pull/51
