### ISSUE TITLE
lein migratus create "migrationName" do not locate into correct migration folder

### ISSUE THREAD

**Issue by ShellOn** [yogthos/migratus#32]
I run :

lein migratus create MigrationName

and it creates the migration file into the project folder ( not into the sub folder )
however i have 

 :migratus {:store :database
           :migration-dir "migrations"
           :db {:classname "org.postgresql.Driver"
                :subprotocol "postgresql"
                :subname ""
                :user ""
                :password ""}}

set into the project.clj , and i tried add the slashes to "migrations" but neither works..

**Comment by lukasspee** [comment]
Migratus looks for the `:migration-dir` in your classpath (see https://github.com/yogthos/migratus/blob/master/src/migratus/database.clj#L80). If it's not there, it apparently just creates the migration files in your project's root.

I ran into the same issue with a Luminus project where the `migrations` folder was directly located in the project's root folder, which was not in the classpath. I fixed the issue by moving the `migrations` folder into the `resources` folder of the project.

**Comment by yogthos** [comment]
This is necessary in order to be able to be able to package the migrations when packaging the application.

**Comment by bimsiq** [comment]
although I have a migration-dir: resources/migrations it still creates the newly created files directly in the project's root folder.
when I run mirgratus/up or /down it looks for them where I declared and I have to manually copy them there.
is this the same deployment issue that @yogthos pointed out ?

**Comment by yogthos** [comment]
the `:migration-dir` key should point to a location relative to the `resources` folder in the project. If it's not specified then it should default to `resources/migrations`.
