### ISSUE TITLE
migrations failing on heroku

### ISSUE THREAD

**Issue by Banashek** [yogthos/migratus#37]
I've been working on an api server (ring/compojure based) and am using migratus for the database migrations (it's awesome!).

I'm having some trouble getting the migrations to run on heroku however, and am given an incredibly difficult to interpret error when attempting the migration.

    heroku run lein migratus migrate --app myapp

    Running lein migratus migrate attached to terminal... up, run.2813 

`Exception in thread "main" java.lang.Exception: Too many arguments to def (impl.clj:35) at clojure.lang.Compiler.analyzeSeq(Compiler.java:5376) at clojure.lang.Compiler.analyze(Compiler.java:5190) at clojure.lang.Compiler.analyze(Compiler.java:5151) at clojure.lang.Compiler.eval(Compiler.java:5428) at clojure.lang.Compiler.load(Compiler.java:5857) at clojure.lang.RT.loadResourceScript(RT.java:340) at clojure.lang.RT.loadResourceScript(RT.java:331) at clojure.lang.RT.load(RT.java:409) at clojure.lang.RT.load(RT.java:381) at clojure.core$load$fn__4519.invoke(core.clj:4915) at clojure.core$load.doInvoke(core.clj:4914) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.core$load_one.invoke(core.clj:4729) at clojure.core$load_lib.doInvoke(core.clj:4766) at clojure.lang.RestFn.applyTo(RestFn.java:142) at clojure.core$apply.invoke(core.clj:542) at clojure.core$load_libs.doInvoke(core.clj:4800) at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invoke(core.clj:542) at clojure.core$require.doInvoke(core.clj:4881) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.tools.logging$eval80$loading__4414__auto____81.invoke(logging.clj:13) at clojure.tools.logging$eval80.invoke(logging.clj:13) at clojure.lang.Compiler.eval(Compiler.java:5424) at clojure.lang.Compiler.eval(Compiler.java:5415) at clojure.lang.Compiler.load(Compiler.java:5857) at clojure.lang.RT.loadResourceScript(RT.java:340) at clojure.lang.RT.loadResourceScript(RT.java:331) at clojure.lang.RT.load(RT.java:409) at clojure.lang.RT.load(RT.java:381) at clojure.core$load$fn__4519.invoke(core.clj:4915) at clojure.core$load.doInvoke(core.clj:4914) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.core$load_one.invoke(core.clj:4729) at clojure.core$load_lib.doInvoke(core.clj:4766) at clojure.lang.RestFn.applyTo(RestFn.java:142) at clojure.core$apply.invoke(core.clj:542) at clojure.core$load_libs.doInvoke(core.clj:4800) at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invoke(core.clj:542) at clojure.core$require.doInvoke(core.clj:4881) at clojure.lang.RestFn.invoke(RestFn.java:457) at migratus.core$eval74$loading__4414__auto____75.invoke(core.clj:14) at migratus.core$eval74.invoke(core.clj:14) at clojure.lang.Compiler.eval(Compiler.java:5424) at clojure.lang.Compiler.eval(Compiler.java:5415) at clojure.lang.Compiler.load(Compiler.java:5857) at clojure.lang.RT.loadResourceScript(RT.java:340) at clojure.lang.RT.loadResourceScript(RT.java:331) at clojure.lang.RT.load(RT.java:409) at clojure.lang.RT.load(RT.java:381) at clojure.core$load$fn__4519.invoke(core.clj:4915) at clojure.core$load.doInvoke(core.clj:4914) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.core$load_one.invoke(core.clj:4729) at clojure.core$load_lib.doInvoke(core.clj:4766) at clojure.lang.RestFn.applyTo(RestFn.java:142) at clojure.core$apply.invoke(core.clj:542) at clojure.core$load_libs.doInvoke(core.clj:4800) at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invoke(core.clj:542) at clojure.core$require.doInvoke(core.clj:4881) at clojure.lang.RestFn.invoke(RestFn.java:421) at leiningen.migratus$eval68$loading__4414__auto____69.invoke(migratus.clj:14) at leiningen.migratus$eval68.invoke(migratus.clj:14) at clojure.lang.Compiler.eval(Compiler.java:5424) at clojure.lang.Compiler.eval(Compiler.java:5415) at clojure.lang.Compiler.load(Compiler.java:5857) at clojure.lang.RT.loadResourceScript(RT.java:340) at clojure.lang.RT.loadResourceScript(RT.java:331) at clojure.lang.RT.load(RT.java:409) at clojure.lang.RT.load(RT.java:381) at clojure.core$load$fn__4519.invoke(core.clj:4915) at clojure.core$load.doInvoke(core.clj:4914) at clojure.lang.RestFn.invoke(RestFn.java:408) at clojure.core$load_one.invoke(core.clj:4729) at clojure.core$load_lib.doInvoke(core.clj:4766) at clojure.lang.RestFn.applyTo(RestFn.java:142) at clojure.core$apply.invoke(core.clj:542) at clojure.core$load_libs.doInvoke(core.clj:4800) at clojure.lang.RestFn.applyTo(RestFn.java:137) at clojure.core$apply.invoke(core.clj:542) at clojure.core$require.doInvoke(core.clj:4881) at clojure.lang.RestFn.invoke(RestFn.java:408) at leiningen.core$resolve_task.invoke(core.clj:208) at leiningen.core$apply_task.invoke(core.clj:258) at leiningen.core$_main.doInvoke(core.clj:329) at clojure.lang.RestFn.applyTo(RestFn.java:139) at clojure.core$apply.invoke(core.clj:542) at leiningen.core$_main.invoke(core.clj:332) at user$eval42.invoke(NO_SOURCE_FILE:1) at clojure.lang.Compiler.eval(Compiler.java:5424) at clojure.lang.Compiler.eval(Compiler.java:5391) at clojure.core$eval.invoke(core.clj:2382) at clojure.main$eval_opt.invoke(main.clj:235) at clojure.main$initialize.invoke(main.clj:254) at clojure.main$script_opt.invoke(main.clj:270) at clojure.main$main.doInvoke(main.clj:354) at clojure.lang.RestFn.invoke(RestFn.java:482) at clojure.lang.Var.invoke(Var.java:381) at clojure.lang.AFn.applyToHelper(AFn.java:178) at clojure.lang.Var.applyTo(Var.java:482) at clojure.main.main(main.java:37) Caused by: java.lang.Exception: Too many arguments to def at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:415) at clojure.lang.Compiler.analyzeSeq(Compiler.java:5369) ... 102 more`

At first I thought it might be an issue with the way the connection string is formatted.

In my local profiles.clj (where it works fine), it looks like this:
   ` :database-url "jdbc:postgresql://localhost:5432/my_db?user=myuser&password=mypass"`
and the db string that heroku gives me is formatted like this:
`postgres://myuser:mypass@myec2server.amazonaws.com:5432/my_db`

I made another environment variable using the credentials from the db that heroku gave me, but formatted in the same style as my local variable, but I still get the same error.

I'm completely baffled as to what the error might be.

Any ideas?

**Comment by yogthos** [comment]
The exception seems to indicate that there is a syntax error `Too many arguments to def (impl.clj:35) `, however it doesn't appear to trace anywhere useful. The only places it references migratus is in namespace definitions.

Some of the things to check on the heroku would be Clojure and Leiningen versions. The other thing to note is that clojure.java.jdbc doesn't work with heroku db connection strings, using something like [conman](https://github.com/carouselapps/to-jdbc-uri) to parse the connection url might help as well.

**Comment by yogthos** [comment]
The [luminus](http://www.luminusweb.net/) template is setup to work with heroku. It might be useful for troubleshooting. You could make a test project with `lein new reagent test-app +postgres` and it's setup with a Heroku Procfile.

**Comment by Banashek** [comment]
Thanks. 

I'll check those out and report back here if I figure it out.

**Comment by yogthos** [comment]
@Banashek  is this still an issue, or can we close it?

**Comment by Banashek** [comment]
Sorry about the delay. 

I'll close this out, it's obviously not a problem with migratus.

Most likely an implementation detail.
