### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by z3roshot** [yogthos/migratus#38]
I have observed that sometimes migratus does not print the correct error message when a migration fails. Specifically I had a syntax error in my SQL and the error reported was not the syntax error. I have created [a repository](https://github.com/z3roshot/migratus_example) that can be used to reproduce this issue. Notice in particular in [the migration file](https://github.com/z3roshot/migratus_example) that the third table create command is missing a comma between the two column types. Consistently, the error message is

`Exception in thread "main" org.postgresql.util.PSQLException: ERROR: relation "test_table" already exists`

instead of the typical error for that sort of syntax error.

In order to reproduce this locally, you just need to checkout my repository and add a typical profiles.clj file with the database_url string defined.

If I can help in any other way, let me know. Thanks!

**Comment by yogthos** [comment]
Hmm it looks like the error is actually generated by the Postgres driver. If the driver doesn't return useful information there's not much you could do to tell whether the query is valid or not unfortunately.

**Comment by z3roshot** [comment]
Ok, thank you @yogthos!

I'll close this then.
