### ISSUE TITLE
Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by kenrestivo** [yogthos/migratus#45]
Using  
```clojure
[migratus-lein "0.2.0"]
```
When running
```sh
lein migratus
```

I get

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
````

I tried adding a logging implementation to my :plugins list, i.e.
```clojure
[ch.qos.logback/logback-classic "1.1.3"]
```

But still get the same error.

I tried adding to the :plugins list:
```clojure
[org.slf4j/slf4j-log4j12 "1.7.9"]
```

Still same error.

**Comment by kenrestivo** [comment]
Nevermind, I got it working by adding to my main project dependencies:

```clojure
[com.fzakaria/slf4j-timbre "0.2"]
````

I really didn't want to have to add slf4j to my main project but I guess it was necessary. Works now.

**Comment by yogthos** [comment]
yeah some internal dependencies use slf4j so this is the best approach

**Comment by kenrestivo** [comment]
I ended up not being able to get that to work, and thanks for explaining it here:
http://yogthos.net/posts/2015-12-26-AOTGotchas.html

I mentioned it here: https://github.com/fzakaria/slf4j-timbre/issues/9

I really would love to have migratus work with timbre, since my entire app is based on timbre, but for now I've been just using migratus blind, i.e. not integrated into my timbre logging.

**Comment by yogthos** [comment]
Yeah it's a bit unfortunate. The bigger concern is that this is a difficult to debug issue, so even if a new version of slf4j-timbre gets released you could end up with a break later down the road if the API in any of the timbre libraries changes. You're also stuck with whatever versions of these libraries slf4j-timbre was compiled against.

From what I can tell there's no way to exclude compiled classes that get generated from the namespaces that get pulled in from dependencies.

**Comment by kenrestivo** [comment]
Hmm. Thinking of hacky workarounds. Maybe: build a local fork of the library with dependencies exactly matching the project into which it is to be included, build, lein install, and then include that? There might even be a way to automate it with lein. But it feels really dirty.

**Comment by yogthos** [comment]
Good news is that the timbre author is aware of the problem and just made a new release https://github.com/fzakaria/slf4j-timbre/issues/8 so things should work in the near future at least.

The safest way would just be to include the code from slf4j-timbre directly in the project, then the aot would happen against your project and everything would be fine. It's not a great long term solution though.
