### ISSUE TITLE
Migratus tries to execute foo.sql~ editor temp files

### ISSUE THREAD

**Issue by kenrestivo** [yogthos/migratus#47]
Is there some way to make Migratus ignore foo.sql~ files left by editors?

It seems to be very confused by them. 

```log4j
5-Nov-06 21:03:08 q400a INFO [slf4j-timbre.adapter] - Starting migrations
15-Nov-06 21:03:08 q400a WARN [slf4j-timbre.adapter] - '20151105234246-geocode-table.down.sql~' does not appear to be a valid migration
15-Nov-06 21:03:08 q400a WARN [slf4j-timbre.adapter] - '20151105234246-geocode-table.up.sql~' does not appear to be a valid migration
15-Nov-06 21:03:08 q400a INFO [slf4j-timbre.adapter] - Ending migrations
```

**Comment by yogthos** [comment]
It's a warning that some files have been found in the migrations folder that aren't going to be run. The intent is to notify the user that some files haven't been used for migrations in case you expected them to be run.

**Comment by kenrestivo** [comment]
Hmm, OK, thanks. I can just ignore them.
