### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by josedonizetti** [yogthos/migratus#52]
can we release the new version with support to destroy?
I can bump the lein-plugin and luminus-template after it.

**Comment by yogthos** [comment]
yeah sure thing, I can update the plugin template as well

**Comment by yogthos** [comment]
actually if you'd like to take a crack at the updates that might be faster :)

**Comment by yogthos** [comment]
and a new version is up on clojars

**Comment by josedonizetti** [comment]
Thank you! I'll go for the templates bump if you don't mind.

**Comment by yogthos** [comment]
:+1:
