### ISSUE TITLE
`create` will put migrations in the root directory if the :migration-dir doesn't exist

### ISSUE THREAD

**Issue by mveytsman** [yogthos/migratus#57]
When I have a config like

```clojure
(def config {:store :database
             :migration-dir "this_is_a_directory_that_doesnt_exist/"
             :migration-table-name "migrations"
             :db "com.mysql.jdbc.Driver"
             :subprotocol "postgresql"
             :subname "//localhost/mydbi"})
```

running

`(migratus.core/create config "my-migration")` will put the migration file in the root directory of my project.

I'm willing to work on this, if you let me know what you think default behavior should be. Should we create the directory, or throw an error?

**Comment by yogthos** [comment]
I think creating the directory would probably be reasonable in this case.

**Comment by yogthos** [comment]
and thanks for taking it on, ping me if you have any questions and I can push out the fix when you have it
