### ISSUE TITLE
Unable to run migrations from uberjar

### ISSUE THREAD

**Issue by derpod** [yogthos/migratus#63]
Hello.

I saw the previous issue on heroku that seemed to get closed out randomly, and a similar issue to the one I'm experiencing https://github.com/luminus-framework/luminus-template/issues/171 on the luminus project.

I can't seem to get migrations to run on heroku.

    lein migratus migrate

fails with 

    SEVERE: Error creating DB connection for
    java.lang.IllegalArgumentException: db-spec null is missing a required parameter

but since I'm just using clojure with migratus and lein-migratus as dependencies instead of the full luminus framework, running

    java -jar <app>.jar migrate

fails with

    Exception in thread "main" java.io.FileNotFoundException: migrate (No such file or directory)

which makes sense since I don't have a migrate function or file.

What is the correct approach for a situation like this?

**Comment by yogthos** [comment]
By  default the migrations are placed in the `resources/migrations` folder. This will be packaged with the application in the jar and should be available on the resource path when the app runs. You should definitely be able to do `java -jar <app>.jar migrate` to run the migrations.

Here's an example session I just ran locally:

```
lein new luminus myapp +h2
lein uberjar
lein uberjar
Compiling myapp.env
Compiling myapp.config
Compiling myapp.core
Compiling myapp.db.core
Compiling myapp.handler
Compiling myapp.layout
Compiling myapp.middleware
Compiling myapp.routes.home
Compiling myapp.routes.services
Created /Users/Yogthos/src/tmp/myapp/target/myapp-0.1.0-SNAPSHOT.jar
Created /Users/Yogthos/src/tmp/myapp/target/myapp.jar
cd target
java -Ddatabase-url="jdbc:h2:./myapp_dev.db" -jar myapp.jar migrate
[2016-03-01 19:45:13,413][INFO][migratus.core] Starting migrations
[2016-03-01 19:45:13,546][INFO][migratus.database] creating migration table 'schema_migrations'
[2016-03-01 19:45:13,927][INFO][migratus.core] Running up for [20160301194240]
[2016-03-01 19:45:13,927][INFO][migratus.core] Up 20160301194240-add-users-table
[2016-03-01 19:45:13,936][INFO][migratus.core] Ending migrations
```

**Comment by derpod** [comment]
so if my migrations are in `resources/db/migrations`

and my project.clj has the correct mapping

    :migratus {:store :database
               :migration-dir "db/migrations"
               :db ~(get (System/getenv) "DB_URL")}

would that make a difference?

**Comment by derpod** [comment]
My project file looks like this:
```
(defproject myapp "0.0.0"
  :description "myapp"
  :url "myapp.com"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [ring/ring-core "1.4.0"]
                 [ring/ring-jetty-adapter "1.4.0"]
                 [compojure "1.4.0"]
                 [ring/ring-jetty-adapter "1.4.0"]
                 [ring/ring-json "0.4.0"]
                 [cheshire "5.5.0"]
                 [com.layerware/hugsql "0.4.2"]
                 [org.postgresql/postgresql "9.4-1201-jdbc41"]
                 [migratus "0.8.13"]
                 [org.slf4j/slf4j-log4j12 "1.7.9"]
                 [environ "1.0.2"]
                 [buddy/buddy-hashers "0.11.0"]
                 [buddy/buddy-sign "0.9.0"]
                 [buddy/buddy-auth "0.9.0"]
                 [metosin/ring-swagger "0.22.4"]
                 [prismatic/schema "1.0.5"]
                 [org.clojure/clojurescript "1.7.170"]
                 [reagent "0.6.0-alpha"]
                 [re-frame "0.7.0-alpha-2"]
                 [re-com "0.8.0"]
                 [secretary "1.2.3"]]
  
  :min-lein-version "2.0.0"

  :source-paths ["src/clj"]

  :migratus {:store :database
             :migration-dir "db/migrations"
             :db ~(get (System/getenv) "DB_URL")}

  :plugins [[lein-ring "0.9.7"]
            [lein-pprint "1.1.1"]
            [migratus-lein "0.2.6"]
            [lein-environ "1.0.2"]
            [lein-cljsbuild "1.1.2"]
            [lein-figwheel "0.5.0-6"]]

  :ring {:handler myapp.core/app
         :nrepl {:start? true
                 :port 9998}}

  :hooks [leiningen.cljsbuild]
  
  :uberjar-name "myapp.jar"

  :figwheel {:repl false}

  :clean-targets ^{:protect false} ["resources/public/js/compiled" "target"]

  :cljsbuild {:builds [{:id "dev"
                        :source-paths ["src/cljs"]
                        :figwheel {:on-jsload "myapp.core/mount-root"}
                        :compiler {:main myapp.core
                                   :asset-path "js/compiled/out"
                                   :output-dir "resources/public/js/compiled/out"
                                   :output-to  "resources/public/js/compiled/app.js"
                                   :optimizations :none
                                   :source-map true
                                   :source-map-timestamp true}}
                       {:id "min"
                        :source-paths ["src/cljs"]
                        :compiler {:main myapp.core
                                   :output-to "resources/public/js/compiled/app.js"
                                   :optimizations :advanced
                                   :closure-defines {goog.DEBUG false}
                                   :pretty-print false}}]}

  :profiles {:dev {:uberjar {:source-paths ^:replace ["src/clj"]
                             :resource-paths ["resources"]
                             :prep-tasks ["compile" ["cljsbuild" "once"]]
                             ;;:hooks [leiningen.cljsbuild] ;; apparently this defined here doesn't work for heroku, needs to be at the root level
                             :env {:production true}
                             :omit-source true
                             :aot :all
                             :main myapp.core
                             :cljsbuild {:builds
                                         {:min
                                          {:source-paths ["src/cljs"]
                                           :jar true
                                           :output-to "resources/public/js/compiled/app.js"
                                           :compiler
                                           {:optimizations :advanced
                                            :pretty-print false}}}}}}})
```

At this point it must be something with my configuration, but I'm not sure what.

Do you happen to see any glaring errors?

I'm not sure how to debug this other than twiddling things around until it works.

**Comment by yogthos** [comment]
I thought Heroku used `DATABASE_URL` for its configuration, at least that's what they mention [here](https://devcenter.heroku.com/articles/heroku-postgresql).

**Comment by yogthos** [comment]
If you're putting the migrations in `:migration-dir "db/migrations"` in the project root then that would be a problem as well. Try removing that key and putting migrations under `resources/migrations`.

**Comment by derpod** [comment]
After switching to `DATABASE_URL` and moving the migration dir, I'm still getting the same error.

If I go and unzip the jar, I do see the files listed
```
./META-INF/leiningen/migratus
./META-INF/leiningen/migratus/migratus
./META-INF/maven/migratus
./META-INF/maven/migratus/migratus
./migrations
./migratus
```

**Comment by derpod** [comment]
After switching to `DATABASE_URL` and moving the migration dir, I'm still getting the same error.

If I go and unzip the jar, I do see the files listed
```
./META-INF/leiningen/migratus
./META-INF/leiningen/migratus/migratus
./META-INF/maven/migratus
./META-INF/maven/migratus/migratus
./migrations
./migratus
```

**Comment by yogthos** [comment]
you should have something like this in the `jar`:

```
migrations/
  20160301225832-add-users-table.down.sql
  20160301225832-add-users-table.up.sql
```

I would also try running `java -Ddatabase-url="..." -jar <app>.jar` in the `target` directory when you build locally to see if you can get migrations to run outside Heroku on the local machine.

The other thing to check is that you do have the database configured correctly on Heroku, and that the `DATABASE_URL` variable is available in the environment.

**Comment by derpod** [comment]
The migrations are in the correct directory.

I tried with the database url specified and got the same error.

I feel like this error doesn't have to do with the migrations themselves though.

`Exception in thread "main" java.io.FileNotFoundException: migrate (No such file or directory)`

to me sounds like somehow the migrate function isn't able to be called.

I'm more familiar with the .Net ecosystem so it might just be my JVM naivety showing right now, but to me the jar seems to be saying that it can't find any function 'migrate' on which it can invoke

**Comment by yogthos** [comment]
The error says that the file called `migrate` couldn't be found. I would take a look at what your `-main` function is doing when it's called. This function is found in the `<app>.core` namespace. The latest template will generate the following code:

```clojure
(defn -main [& args]
  (cond
    (some #{"migrate" "rollback"} args)
    (do
      (mount/start #'myapp.config/env)
      (migrations/migrate args (env :database-url))
      (System/exit 0))
    :else
    (start-app args)))
```

So, when one of the arguments is `"migrate"` or `"rollback"`, then it calls `migrations/migrate` with the `args` and the databse url. Older versions of the template had the migrations logic in the `<app>.db.migrations` namespace, so the `-main` might have called that.

I would take a look at what happens in your project when the app is passed the `migrate` argument on the command line.

**Comment by derpod** [comment]
This looks like just an issue with my project as an uberjar, I can't even get it to accept arguments if I put your main function in.

Again I'm not using luminus, just plain migratus, so I didn't have a main function that looked like that.

I'll close this out since it's not related to migratus, and I'll try to figure out why my uberjar won't take arguments.

At this point I just changed main to print out any args I pass, and it just opens a repl when I run it.

Sorry to waste your time with the user error.

**Comment by yogthos** [comment]
no worries, glad I got you pointed in the right direction :)

**Comment by oubiwann** [comment]
I ran into this issue as well. Symptoms:
 * Running init and migrate in a REPL  worked
 * Running init and migrate from an uberjar failed

Debugging showed me that, at least for my setup, the `init.sql` script wasn't found:

```clj
user=> (mb/find-init-script "migrations/" "init.sql")
nil
```

However, this did fine the init script:

```clj
user=> (mb/find-init-script "migrations/" "migrations/init.sql")
#object[java.util.jar.JarFile$JarFileEntry 0x202b5293 "migrations/init.sql"]
```

As you might infer, my setup has all migratus files in "resources/migrations". This arragement worked for when using `lein` and the source code, but didn't work when using just a `.jar` deployment. It wasn't immediately clear to me from reading the docs what the assumed relative path for `init.sql` was.

I attempted to run migratus with an updated  configuration with `:init-script "migrations/init.sql`, but this didn't work:

```
2017-03-02T16:33:49.141 [main] ERROR ngap.onboarding.db.migrate:27 - \
Cannot open <#object[java.util.jar.JarFile$JarFileEntry \
 0x3e371088 "migrations/init.sql"]> as an InputStream.
```

Neither did `:init-script "resources/migrations/init.sql` (tried it on a whim, just in case):

```
2017-03-02 16:39:19,761 [main] ERROR migratus.database - \
could not locate the initialization script ' resources/migrations/init.sql ' 
```

Given the size of the project, my preference is to keep individual files out of the top-level resources directory, so I next tried moving all my migration files into `resources/db/migrations` and the init script to `resources/db/init.sql`, updating the configuration accordingly. Similar error as the first one:

```
2017-03-02T16:45:46.044 [main] ERROR ngap.onboarding.db.migrate:27 - \
Cannot open <#object[java.util.jar.JarFile$JarFileEntry \
0x3e371088 "db/init.sql"]> as an InputStream.
```

I did try moving the init script to just `resources/init.sql`, but still got the same error (Cannot open as an InputStream).

At this point, I hopped into a REPL running against the .jar; as expected so far:

```clj
user=> (md/find-init-script "db/migrations" "init.sql")
#object[java.util.jar.JarFile$JarFileEntry 0x5ce8d869 "init.sql"]
user=> (slurp (md/find-init-script "db/migrations" "init.sql"))
IllegalArgumentException Cannot open <#object[java.util.jar.JarFile$JarFileEntry \
0x7a1234bf "init.sql"]> as an InputStream.  clojure.java.io/fn--9498 (io.clj:167)
```

I've had to do this in other projects, though, and I never needed to use the `java.util.jar` lib; just identifying the file as a resource was enough. Lilkewise here:

```clj
(slurp (clojure.java.io/resource "init.sql"))
```

Note that there doesn't seem to be any problem with the migration files, just the `init.sql` file. Looking at the code (briefly), I see that they are handled differently. But maybe this could all be simplified to use `clojure.java.io/resource`? 

Not sure if @derpod ever found a solution to his problem, so I though it might, at the very least, be worth making some notes here in the event that others have this problem and end up here.

@yogthos: Great tool, btw :-) Thanks! Hope to get the .jar deployment configured properly/fixed!

**Comment by oubiwann** [comment]
Update to/note for my last comment: 

All testing is done in a Docker image that doesn't have the source code present, only the .jar files .... so guaranteed isolation from filesystem project resources, etc.

**Comment by oubiwann** [comment]
I've got a tiny fix in place that seems to be working. I will test on a few more isolated deployments, and then submit a PR.

**Comment by yogthos** [comment]
@oubiwann thanks for digging into this. 👍

**Comment by oubiwann** [comment]
@yogthos You bet! Thanks for the quick merge and release (we're using it now 😄)

**Comment by yogthos** [comment]
:tada:
