### ISSUE TITLE
Disable transactions ala carte?

### ISSUE THREAD

**Issue by emidln** [yogthos/migratus#65]
Some DDL commands are not able to be executed in transactions, although the database supports other DDL commands in transactions. An example is `alter type ... add` in Postgres. We need some way of disabling this per-module. 

~~As a workaround, I think I could do:~~

``` sql
-- this doesn't actually work...
commit;
--;;
alter type ... add ....;
--;;
begin;
```

~~But this seems like a gross hack.~~ And doesn't work.

**Comment by yogthos** [comment]
One approach could be to use comments the way [HugSQL](http://www.hugsql.org/) does, e.g:

```
--;;
-- :disable-transaction
...
```

**Comment by ricardojmendez** [comment]
@yogthos Any update on this? I just triggered it myself, precisely with an ALTER TYPE ... ADD VALUE IF NOT EXISTS.

**Comment by yogthos** [comment]
I haven't looked, if the comment idea makes sense, that wouldn't be hard to implement.

**Comment by ricardojmendez** [comment]
I'd say that makes sense. Given how rare this is, it should probably be a "least amount of effort" thing. Say, it would be just fine if it's even file-wide.

**Comment by ricardojmendez** [comment]
From Slack, for reference:

	ricardo [10:25 PM]  
	Hmm. This is fully clearing out SQL comments.
	[10:26]  
	And by when it gets to line 71 (on database.clj), it has already initialized a transaction.
	
	yogthos [10:27 PM]  
	yeah
	[10:27]  
	so have to hook into it before it gets rid of the comments to check if there are any special ones
	
	[10:28]  
	maybe can add something like `read-metadata` that will check the comments for any metadata
	
	ricardo [10:34 PM]  
	That’s what I was thinking - this needs some pre-processing. Maybe we can assume that all metadata notes will be contained on the first line.
		
	yogthos [10:35 PM]  
	I’d just split the comments by new line and see if any start with `— : `
	[10:36]  
	then could have a map with the keys that map to those

**Comment by gleenn** [comment]
Did this ever get resolved? Would love to be able to add indexes concurrently to a postgres database which also can't be inside a transaction block. The ```-- :disable-transaction``` sounds like a great idea.

**Comment by yogthos** [comment]
Still open, if you'd be up for doing a PR that would be great. Otherwise, I'll try get around to it when I get a chance.
