### ISSUE TITLE
Unecessary dependency

### ISSUE THREAD

**Issue by Gonzih** [yogthos/migratus#66]
Hi there,

Just started using your library and I have one concern: is camel-snake-kebab really needed as a dependency? Do you think it makes sense to remove it and re-implement functionality of one function that is used in this project? I can submit PR if you agree that this is ok thing to do.

Cheers,
Max

**Comment by yogthos** [comment]
Yeah sure, I think that's reasonable and will be glad to accept a pr for this.

**Comment by ndrluis** [comment]
This issue could be closed in favor of https://github.com/yogthos/migratus/commit/579b859b2f10c3c0c7186e625135ceb9b5f67764#diff-87ae34f382f33d939b8395e3eeee5b81

**Comment by yogthos** [comment]
👍

**Comment by Gonzih** [comment]
Awesome! Thanks
