### ISSUE TITLE
Version 0.8.14 in README and on Clojars

### ISSUE THREAD

**Issue by Ethan826** [yogthos/migratus#67]
Hi, I'm pretty new to this and haven't opened an issue before, so please forgive me if I am botching the protocol. Yesterday's commit fixed a problem with the `clojure.java.jdbc` breaking changes in version 0.6.0, but neither the README nor the Clojars jar has been updated. See my question at https://stackoverflow.com/questions/36733964/migratus-java-lang-character-cannot-be-cast-to-clojure-lang-named/36798455.

Thanks.

**Comment by yogthos** [comment]
I haven't pushed the changes out to Clojars yet, as I wanted to do a bit more testing. It does look fine though from what I can tell, so I'll go ahead and push it out.

**Comment by yogthos** [comment]
The latest should be on Clojars and working with the latest clojure.java.jdbc, if anything is still a problem then definitely let me know.

**Comment by Ethan826** [comment]
Thanks!
