### ISSUE TITLE
Can (m/up ..) and (m/down ...) return non-nil on success?

### ISSUE THREAD

**Issue by theronic** [yogthos/migratus#73]
I noticed that `(migratus/down config 2016...)` returns nil whether a migration ran or not. This caught me when I made a typo in my manual call during my dev environment. It would be helpful to debug if it returned a non-nil value if the migration file was found and a statement was ran.

**Comment by yogthos** [comment]
yeah that seems like a good idea

**Comment by yogthos** [comment]
Just pushed out a new version that should return `true` when up/down commands run. Let me know if that looks good.

**Comment by dijonkitchen** [comment]
@theronic any updates or should it be closed?

**Comment by yogthos** [comment]
I'm closing this one, and we can reopen if needed.
