### ISSUE TITLE
postgresql "9.3-1102.jdbc41" errors on migration

### ISSUE THREAD

**Issue by rcsole** [yogthos/migratus#78]
Using `postgresql "9.3-1102.jdbc41"`, an exception gets thrown:

`Exception in thread "main" java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc4.Jdbc4Connection.getSchema() is not yet implemented.`

Could this be related to this change? https://github.com/yogthos/migratus/commit/7e0b6c13a68f8a62716e852c4733d2c86621b9fd

**Comment by yogthos** [comment]
yeah appears so, I guess could check for that specific exception as well then

**Comment by yogthos** [comment]
let me know if this does the trick https://github.com/yogthos/migratus/commit/204f8f8a5eda007dabd6f8d464d804dbd4ec323e
