### ISSUE TITLE
migratus/pending-list throws "db-spec null is missing a required parameter"

### ISSUE THREAD

**Issue by pate** [yogthos/migratus#82]
When I run `(migratus/pending-list config)` with Migratus `v0.8.25`, the following exception is thrown:

```
java.lang.IllegalArgumentException: db-spec null is missing a required parameter
```
This is my config:
```
(def config {:store                :database
             :migration-dir        "migrations"            ; lives inside ~/resources/
             :migration-table-name "migrations"
             :db                   "postgresql://localhost:5432/myproject"})
```

**Comment by yogthos** [comment]
Ah ok, the `pending-list` function wasn't running the connect statement. I just checked in a fix, if you can try to confirm that it works, I can push out a new version.

**Comment by yogthos** [comment]
released the new version with a fix
