### ISSUE TITLE
Migratus does not delete migration ids from migrations table when downgrading

### ISSUE THREAD

**Issue by pate** [yogthos/migratus#83]
The sequence "upgrade, downgrade (all the way), upgrade" breaks because downgrade does not remove migration IDs from `migrations` table and the subsequence upgrade won't re-run the migrations.

**Comment by yogthos** [comment]
Whenever a down migration is run successfully the [id is marked as incomplete](https://github.com/yogthos/migratus/blob/687f13f936f7a848446c8eb329909dbd9e3b0164/src/migratus/database.clj#L92), this will trigger the migration to be run.
