### ISSUE TITLE
Basic migrations?

### ISSUE THREAD

**Issue by coyotespike** [yogthos/migratus#88]
How do basic migrations work? There seems to be some machinery to track migrations which isn't allowing me to what I'm attempting.

I thought running `migratus/up config <numberhere>` and then `migratus/down config <numberhere>` would create and then drop a table. However, the table is created but not dropped. That is, the `up` seems to work but not the `down`. In fact, after dropping the table manually, running `down` _creates_ the table.

I've confirmed that running the SQL in the `down` file drops the table when run in `psql` at the command line. I'm running this programmatically, not from the command line.

**Comment by coyotespike** [comment]
Well of course I may have solved it a few minutes after posting an issue, though I tried it for hours before!

The unexpected behaviour appears to have come from two sources. 

First, I put my migrations in `migrations/`, instead of in `resources/migrations/`. I was confusing Ragtime with Migratus.

Second, my config looked like this:
```  
(def config {:store                :database
             :migration-dir        "migrations/"
             :init-script          "init.edn"
             :migration-table-name "quux"
             :db {:classname   (env :driver-class)
                  :subprotocol "postgres"
                  :subname     (env :database-name)}})
```
Because I specified `quux`, Migratus appears to have kept creating this table despite my attempted drops. Removing that key allowed the table to stay dropped.

**Comment by yogthos** [comment]
The migrations are expected to be on the resource path, so `migrations` would be the name if the files are found under `resources/migrations`. Also, note that this is the default name migratus looks for and can be omitted.

Migratus tracks the status of migrations using the table specified using the `:migration-table-name` key. It defaults to using `schema_migrations` when the key is omitted. When it can't find the migrations table, it will create one before doing anything else. Hence the behavior of the table being recreated.

**Comment by coyotespike** [comment]
That makes sense now, I just wasn't aware of it. Good to know I can omit the `:migration-dir` key if that ever takes my fancy. Thanks very much for the help!
