### ISSUE TITLE
Lock migrations in MySQL

### ISSUE THREAD

**Issue by lsnape** [yogthos/migratus#94]
We applied a migration to our MySQL-backed site today that resulted in a few exceptions in our production logs, caused by the migration being applied by both instances that were spinning up at the same time.

The reason for this, I believe, is because MySQL doesn't support transactional DDL (sigh), and thus every instance competes for the migration until the id appears in the migrations table.

I think we could prevent this from happening by setting the isolation level to 'SERIALIZABLE' and inserting the migration id _before_ the migration takes place. It might also need some more thought. I'm happy to submit a PR for this when a decision is made.

**Comment by yogthos** [comment]
Sure, that sounds like it would be a useful feature. I do think you're correct that MySQL doesn't support transactional DDL, so setting the migration ID would provide a way for the other instance to know that the migration is happening.

**Comment by dijonkitchen** [comment]
Looks like this was closed in #95.

**Comment by yogthos** [comment]
Yup, looks like it. 👍
