### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by scgilardi** [yogthos/migratus#96]
It appears that the most recent release is 0.8.32 while the most recent tag is 0.7.0.

Tagging releases is helpful, especially when researching the behavior of older releases.

Please tag the releases between 0.7.0 and now and new releases going forward.

**Comment by yogthos** [comment]
I'll take a look at tagging the releases. The only major change since 0.7.0 release was to update to the current clojure.java.jdbc API. However, user facing API hasn't had any breaking changes since then.

**Comment by jumarko** [comment]
@yogthos I'm looking into this issue in scope of CodeTriage. However, I don't see how could I help with this one. This is probably an ongoing "release process effort".

I agree that it's beneficial to create a new tag for each release (it really doesn't matter how many changes there were). I usually do it like this:
```
git tag -a migratus-x.y .z 9fceb02 -m "Message here"
```
When you create a new tag, the GitHub will automatically add it to the "Release" tab on repo page together with a compressed archive containing the source code.

Would you mind creating the missing tags and following the practice in the future?
After that, this issue could be closed.

**Comment by yogthos** [comment]
@jumarko just have to find the time to go back and find all the releases to tag them, but I definitely could start doing this going forward

**Comment by scgilardi** [comment]
I pulled the sha-1 values for each untagged release from maven and made a shell script to do the tagging. Please consider running it and then pushing tags to github. It looks like there are some cases where multiple maven releases have the same sha-1, and some cases where the project.clj version doesn't match the release version of the jar.

Using some kind of automation in the releases would help keep those versions in sync. I've used the lein release command in the past to help with this (https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#releasing-simplified)

```
# note these revisions have duplicate sha-1 values

# 0.8.4: project.clj says 0.8.3
# 0.8.17: project.clj says 0.8.16
# 0.8.20: project.clj says 0.8.19

git tag -a v0.8.0 -m "release 0.8.0" c2ef268755b853bc3f135d0e6fc1048adba59b93
git tag -a v0.8.1 -m "release 0.8.1" 8512bbf84d9fc3f7578ee04abd96c8315998bd37
git tag -a v0.8.2 -m "release 0.8.2" a2f9265945d4bcb847f20a7f4568b1bc43da2ab2
git tag -a v0.8.3 -m "release 0.8.3" 1c61bf266a3ee5a3660de0c60c1bd8822b63a5a4
git tag -a v0.8.4 -m "release 0.8.4" 1c61bf266a3ee5a3660de0c60c1bd8822b63a5a4
git tag -a v0.8.5 -m "release 0.8.5" 5366960bb7f9486ae043c308216939ada8e4bb05
git tag -a v0.8.6 -m "release 0.8.6" 856c5e88547ac16f2f2d19de1ee6f199a689b274
git tag -a v0.8.7 -m "release 0.8.7" 76b71e102ecc2ebc7d2ba0ab6c09d3b1446c4fe4
git tag -a v0.8.8 -m "release 0.8.8" bd1d1fb23db6301949f2a34e71a4bf98915ea2b1
git tag -a v0.8.9 -m "release 0.8.9" be6ab39391fe1aaaed255b9173b2efd1c59b481b
git tag -a v0.8.10 -m "release 0.8.10" 02eff8758893aa7e969c0e6d8f63f211f9a63480
git tag -a v0.8.11 -m "release 0.8.11" 92a289f79529a3909e1859b6312afc9a41c6fd1f
git tag -a v0.8.12 -m "release 0.8.12" 702b5b5c5ea24f642c4b10b4e03dcf41597bee8b
git tag -a v0.8.13 -m "release 0.8.13" 56607232bd7faa084e7c755fdf1f2cbc68677f69
git tag -a v0.8.14 -m "release 0.8.14" 6355209ade2f17b1b833caf4da9e23736206353a
git tag -a v0.8.15 -m "release 0.8.15" 29c4753bf8a454b0d31b0f379a8a63b4c9cdd618
git tag -a v0.8.16 -m "release 0.8.16" 579b859b2f10c3c0c7186e625135ceb9b5f67764
git tag -a v0.8.17 -m "release 0.8.17" 579b859b2f10c3c0c7186e625135ceb9b5f67764
git tag -a v0.8.18 -m "release 0.8.18" 94e38769ef761b725714395df5f032c69a25a74e
git tag -a v0.8.19 -m "release 0.8.19" 7e0b6c13a68f8a62716e852c4733d2c86621b9fd
git tag -a v0.8.20 -m "release 0.8.20" 7e0b6c13a68f8a62716e852c4733d2c86621b9fd
git tag -a v0.8.21 -m "release 0.8.21" 31ffc36dafd9d8fc628b54d72a4b4ecd0dcdbc47
git tag -a v0.8.22 -m "release 0.8.22" 204f8f8a5eda007dabd6f8d464d804dbd4ec323e
git tag -a v0.8.23 -m "release 0.8.23" 78c58ef273a12df864cafb7e27fce70f798b5a92
git tag -a v0.8.24 -m "release 0.8.24" e0564793234c75eeb589c2d541e363221ac214a9
git tag -a v0.8.25 -m "release 0.8.25" 7aedc8b57ecd79cef076e46b6c5550442cf510fb
git tag -a v0.8.26 -m "release 0.8.26" 83b0ca156e1d949dcc251fe58a841f8523baafe3
git tag -a v0.8.27 -m "release 0.8.27" 897456c90cff5cf2ad0da286be4ed78367e32438
git tag -a v0.8.28 -m "release 0.8.28" 77f74ff59305242dfd4c62b52b2595b06c4cbb1a
git tag -a v0.8.29 -m "release 0.8.29" 80ab9577a27cd917a92641c8f75023712919615c
git tag -a v0.8.30 -m "release 0.8.30" 4694c1104b128bc6fb499c853b0d4e5892a2f525
git tag -a v0.8.31 -m "release 0.8.31" b9f1012624823dfe025420763f1461b345fb96f3
git tag -a v0.8.33 -m "release 0.8.33" 14cdcd7e07e684e9c441fc335925ab6198b5eefa
```

**Comment by yogthos** [comment]
Thanks for making the script, and automating this would definitely be the way to go. I've run the script and pushed the tags. Not sure what happened with the duplicate hashes off top of my head unfortunately.

I'll take a look at using the release task in the future.

**Comment by scgilardi** [comment]
You're welcome. Thanks for taking care of that. I'm happy to close this issue as resolved.

**Comment by yogthos** [comment]
Thanks for spearheading this.
