### ISSUE TITLE
Allow use; statements in migrations.

### ISSUE THREAD

**Issue by kenrestivo-stem** [yogthos/migratus#98]
This migration fails on migratus:

```sql
use test;
--;;
CREATE TABLE IF NOT EXISTS quux(id bigint, name varchar(255));
--;;
CREATE INDEX quux_name on quux(name);

```

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'test.schema_migrations' doesn't exist
     SQLState: "42S02"
    errorCode: 1146
                            java.sql.BatchUpdateException: Table 'test.schema_migrations' doesn't exist
             SQLState: "42S02"
            errorCode: 1146
    largeUpdateCounts: [-3]
         updateCounts: [-3]
```
I'm connecting with these credentials:

```clojure
{:store :database
              :migration-dir "migrations"
              :migrations-table-name "migrations"
              :db {:classname "com.mysql.jdbc.Driver"
                   :subprotocol "mysql"
                   :subname "//localhost/migratus"
                   :user "root"
                   :password ""}}
```

The schema_migrations table is in migratus database, not test.

```
mysql> use migratus;
use migratus;
Database changed
mysql> show tables;
show tables;
+--------------------+
| Tables_in_migratus |
+--------------------+
| schema_migrations  |
+--------------------+
1 row in set (0.00 sec)

mysql> explain schema_migrations;
explain schema_migrations;
+-------+------------+------+-----+---------+-------+
| Field | Type       | Null | Key | Default | Extra |
+-------+------------+------+-----+---------+-------+
| id    | bigint(20) | NO   | PRI | NULL    |       |
+-------+------------+------+-----+---------+-------+
1 row in set (0.00 sec)
```

It looks like this is the problem:

```clojure
(defn mark-complete [db table-name id]
  (log/debug "marking" id "complete")
  (sql/insert! db table-name {:id id}))
```

It doesn't execute inside a transaction that can change databases, nor does it specify the database.table to be used.

It looks like migratus can't handle doing migrations on several different databases.

This is a blocker for us; I'd be happy to do the work to enable this functionality and contribute it as a patch.

Is there any recommended approach? clojure.jdbc has lots of little bells and whistles to use.

**Comment by yogthos** [comment]
A PR for this would be great, the only concern is to retain backwards compatibility. One approach could be to make this a configuration option. Let me know if you had an idea in mind for how you'd like this to work.

**Comment by kenrestivo-stem** [comment]
The tricky bit will be to make it engine-independent. We use MySQL here but I could test on a couple different engines.

I was thinking of the following:

```clojure
:migration-database-name "baz"
```
If that is present in the config, then modify mark-complete and mark-not-complete functions to change databases prior to doing the sql/insert! call.

Seem reasonable?

**Comment by yogthos** [comment]
Yeah that seems like it would be the way to do it, and since it's opt-in it won't affect databases that don't support this. Although, I think that being able to set the database is pretty standard.

**Comment by kenrestivo-stem** [comment]
OK, my work in progress is here https://github.com/yogthos/migratus/compare/master...kenrestivo-stem:feature/support-use . Testing.

**Comment by kenrestivo-stem** [comment]
Turns out there's no need for any code changes. 

https://github.com/yogthos/migratus/pull/99

**Comment by yogthos** [comment]
👍
